Repository dataware-tools/pydtk, pull requests merged in 2021-08, with the labels that each got.

#84 Fix the bug that cascaded tables were dropped before `save()` is called
  pydtk/db/v4/handlers/__init__.py
  pydtk/db/v4/handlers/meta.py
  test/test_db.py
Labels: approved, lgtm, size/M

#86 Pre-install `jq` in docker images
  docker/base/ubuntu-18.04-ros.Dockerfile
  docker/base/ubuntu-18.04.Dockerfile
  docker/base/ubuntu-20.04-ros.Dockerfile
  docker/base/ubuntu-20.04.Dockerfile
Labels: approved, lgtm, size/XS

#85 Status checker
  pydtk/bin/cli.py
  pydtk/bin/sub_commands/status.py
Labels: approved, kind/feature, lgtm, size/M

#87 Installer
  install-pydtk.py
Labels: approved, lgtm, size/L

#88 Support MontyDB
  poetry.lock
  pydtk/db/v4/engines/montydb.py
  pydtk/db/v4/handlers/meta.py
  pyproject.toml
  test/test_db.py
Labels: approved, lgtm, size/L

#89 Image model
  pydtk/models/image.py
  test/records/image_model_test/sample.png
  test/records/image_model_test/sample.png.json
  test/test_models.py
Labels: kind/feature, approved, lgtm, size/L, area/toolkit

#90 Fix `generate_contents_meta` of GenericJsonModel
  pydtk/models/json_model.py
Labels: approved, size/XS, lgtm

#92 Minor fix
  pydtk/bin/sub_commands/db.py
  pydtk/models/image.py
Labels: approved, size/XS, lgtm

#91 Enrich options of function `read` in MontyDB
  pydtk/db/v4/engines/montydb.py
  test/test_db.py
Labels: approved, size/M

#93 Pre-install ROS-related dependencies in docker images
  .dockerignore
  README.md
  docker-entrypoint.sh
  docker/dev/ubuntu-ros.Dockerfile
  docker/runtime/ubuntu-ros.Dockerfile
Labels: approved, size/S, lgtm
