Repository dataware-tools/pydtk, pull requests merged in 2021-07, with the labels that each got.

#65 Default to `allowDiskUse=True` in MongoDB
  pydtk/db/v4/engines/mongodb.py
Labels: approved, size/XS

#66 Set default to `limit=20` when listing resources with CLI
  pydtk/bin/sub_commands/db.py
Labels: approved, size/XS

#67 Reflect `offset` on `read()` to DBHandler.df
  pydtk/db/v4/handlers/__init__.py
  test/test_db.py
Labels: approved, size/M

#68 Support specifying model in CLI
  pydtk/bin/sub_commands/model.py
  test/test_cli.py
Labels: approved, size/M

#69 Fix the bug that option `--content` had no effect in CLI
  pydtk/bin/sub_commands/model.py
  pydtk/models/__init__.py
  pydtk/models/movie.py
  pydtk/models/pointcloud/pcd.py
  test/test_cli.py
Labels: approved, size/M

#70 Support generating metadata of video files
  pydtk/models/movie.py
Labels: approved, size/M

#74 Fix the bug that dtype of the input data was not fixed
  pydtk/conf/v4.yaml
  pydtk/db/v4/handlers/__init__.py
  test/test_db.py
Labels: approved, size/M

#75 overwrite option (command: db add)
  pydtk/bin/sub_commands/db.py
  pydtk/db/v4/handlers/__init__.py
  test/test_cli.py
Labels: approved, size/L

#77 Add feature to check PEP515 in CLI
  pydtk/bin/cli.py
  test/test_cli.py
Labels: approved, lgtm, size/M

#78 Add command `version` in CLI
  pydtk/bin/cli.py
Labels: approved, size/XS

#79 Hide tracebacks in CLI unless `--verbose` option is set
  pydtk/bin/cli.py
Labels: approved, size/XS

#80 Loadable checks for different models
  pydtk/models/__init__.py
  pydtk/models/movie.py
Labels: approved, kind/bug, lgtm, size/S
